# This docker-compose file will assume that encryption/decryption key is available in the present working directory.
# Run ./prepare-env.sh script to create key.
version: "3.3"
services:
  app-receiver:
    build: ./app-receiver
    image: app-receiver:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - type: volume
        source: ./output
        target: /usr/src/app-receiver/output
      - type: bind
        source: ./key
        target: /run/secrets/decryption_key
  app-sender:
    build: ./app-sender
    image: app-sender:latest
    volumes:
      - type: volume
        source: ./input
        target: /usr/src/app-sender/input
      - type: volume
        source: ./status-db
        target: /usr/src/app-sender/status-db
      - type: bind
        source: ./key
        target: /run/secrets/encryption_key
    environment:
      - RECEIVER_ADDRESS=devopsassignmentpythonanddocker_app-receiver_1
volumes:
  output: {}
  input: {}
  status-db: {}
  key: {}
